# Generated by Django 3.2 on 2021-04-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesettings',
            options={'verbose_name': 'Настройку', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tlg_message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
