# Generated by Django 3.2 on 2021-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_auto_20210428_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesettings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AddField(
            model_name='telesettings',
            name='tlg_chatname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название чата'),
        ),
    ]
